name: ocular-pathology-classification
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - scikit-learn
  - numpy
  - jupyterlab
  - matplotlib
  - tqdm
  - notebook
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - pip:
    - kaggle
    - python-dotenv
    - -e .